package com.tupleinfotech.productbarcodescanner.util

object AlertMsgs {

    val internetConnection                      =           "The Internet connection appears to be offline."
    val emailMissing                            =           "Please enter email address"
    val phoneMissing                            =           "Please enter phone number"
    val passMissing                             =           "Please enter password"
    val oldPassMissing                          =           "Please enter old password"
    val conPassMissing                          =           "Please enter password again"
    val passnotSimlar                           =           "Old password and new password can't be similar"
    val invalidEmailorPhone                     =           "Please enter valid email or phone number"
    val invalidEmail                            =           "Please enter valid email"
    val invalidName                             =           "Please enter valid Name"
    val invalidPhone                            =           "Please enter valid phone number"
    val failService                             =           "Something went wrong. Please try again later !!"
    val missingValue                            =           "Please enter email or phone number"
    val passNotMatch                            =           "Passwords doesn't match"
    val oldPassNotMatch                         =           "Old password doesn't match"
    val zipCodeMissing                          =           "Please enter zipcode"
    val invalidZipCode                          =           "Please enter valid zip code"
    val BarcodeDetectFailed                     =           "Could not detect barcode!"
    val SignOut                                 =           "Are you sure you want to log out?"
    val firstNameMissing                        =           "Please enter first name"
    val lastNameMissing                         =           "Please enter last name"
    val termsNotAgree                           =           "Please agree to terms and conditions"
    val error                                   =           "Error"
    val appNotStart                             =           "App can't be started"
    val appNotLoad                              =           "App can't be loaded, Try again later"
    val closeApp                                =           "Want to close the application ?"
    val passwordcontaindigit                    =           "Password should contain at least 1 digit"
    val passwordcontainlowercase                =           "Password should contain at least 1 lower case letter"
    val passwordcontainuppercase                =           "Password should contain at least 1 upper case letter"
    val passwordcontainletter                   =           "Password should contain a letter"
    val passwordcontainspecialcharacter         =           "Password must contain a Special character"

}